name: deploy
run-name: CI/CD
on:
  push:
    branches: [dev]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image udagram-api-feed from this repo
        run: docker build -t udagram-api-feed ./udagram-api-feed

      - name: Tagging Image udagram-api-feed from this repo
        run: docker tag udagram-api-feed datndd260897/udagram-api-feed:lastest

      - name: Build Docker Image udagram-api-user from this repo
        run: docker build -t udagram-api-user ./udagram-api-user

      - name: Tagging Image udagram-api-user from this repo
        run: docker tag udagram-api-user datndd260897/udagram-api-user:lastest

      - name: Build Docker Image udagram-frontend from this repo
        run: docker build -t udagram-frontend ./udagram-frontend

      - name: Tagging Image udagram-frontend from this repo
        run: docker tag udagram-frontend datndd260897/udagram-frontend:lastest

      - name: Build Docker Image udagram-reverseproxy from this repo
        run: docker build -t udagram-reverseproxy ./udagram-reverseproxy

      - name: Tagging Image udagram-reverseproxy from this repo
        run: docker tag udagram-reverseproxy datndd260897/udagram-reverseproxy:lastest

      - name: Push Docker Image udagram-api-feed from this repo
        run: docker push datndd260897/udagram-api-feed:lastest

      - name: Push Docker Image udagram-api-user from this repo
        run: docker push datndd260897/udagram-api-user:lastest

      - name: Push Docker Image udagram-frontend from this repo
        run: docker push datndd260897/udagram-frontend:lastest

      - name: Push Docker Image udagram-reverseproxy from this repo
        run: docker push datndd260897/udagram-reverseproxy:lastest
